#!/usr/bin/env bash

pushd .
cd data/raw-data/

ls *.csv | sed 's/^.*/<a href="&">&<\/a><br\/>/' > raw.html

ls *.txt | cut -d'.' -f 1 > tmp1
ls *.txt | while read i; do echo `cat $i`; done > tmp2
echo 'sequence,crawl_date' > crawl_info.csv
paste -d, tmp1 tmp2 >> crawl_info.csv
rm -f tmp1 tmp2

awk 'FNR==1 && NR!=1{next;}{print}' 1890*.csv > all.csv
DATE=`date +%Y-%m-%d`
xsv search -s produced $DATE all.csv | xsv select id > produced-$DATE.csv

popd
