#!/usr/bin/env bash

pushd .
cd data/raw-data/

ls *.csv | sed 's/^.*/<a href="&">&<\/a><br\/>/' > raw.html

ls *.txt | cut -d'.' -f 1 > tmp1
ls *.txt | while read i; do echo `cat $i`; done > tmp2
echo 'sequence,crawl_date' > crawl_info.csv
paste -d, tmp1 tmp2 >> crawl_info.csv
rm -f tmp1 tmp2

awk 'FNR==1 && NR!=1{next;}{print}' 18902*.csv > all.csv

xsv select produced,mailed,delivered all.csv \
 | xsv frequency \
 | xsv sort -s value \
 | xsv sort -s field \
 | xsv search -s value "2018*" > stat.csv

DATE=`date +%Y-%m-%d`
xsv search -s produced $DATE all.csv | xsv select id > produced-$DATE.csv
YESTERDAY=$(date -d "-1 days" +%Y-%m-%d)
xsv search -s produced $YESTERDAY all.csv | xsv select id > produced-$YESTERDAY.csv

popd
